### ISSUE TITLE
User popup does not work

### ISSUE THREAD

**Issue by geraldbigot** [tsolucio/coreBOSEmployee#2]
user popup screen doesn't work when there are more than one page of users

**Comment by joebordes** [comment]
This was because the module was installed under the wrong menu (Settings).
Fixed: 34433146af19f8c09d8e103b6d27891d9e0a9d6b

**Comment by geraldbigot** [comment]
In the Menu config ?

Thank you.

Gérald Bigot
Intégrateur CRM / WEB
Mob :   06 51 96 88 10
Tel :   02 22 06 80 28
Fax :   02 22 06 84 90

**Comment by joebordes** [comment]
No, not the menu configurator but the actual installation of the module. When you install a module it is assigned a parent menu which is used for some additional checks in the application but you can then put it wherever you want.

In your case we had to go directly into the database and change the menu from Settings to Tools. You don't have to do anything more.

**Comment by geraldbigot** [comment]
Understood. Thanks.

Gérald Bigot
Intégrateur CRM / WEB
Mob :   06 51 96 88 10
Tel :   02 22 06 80 28
Fax :   02 22 06 84 90
